### ISSUE TITLE
Internet error! 503 Service Unavailable

### ISSUE THREAD

**Issue by mulaiko** [c2h2/tts#11]
Tried using your gem via rails console -  getting error in issue title. Could you assist in solving this issue?

**Comment by eriknomitch** [comment]
+1

**Comment by b1nary** [comment]
Had that on the first try and it worked with a curl request directly afterwards. Not sure if it is just the rate-limit.

**Comment by furqan85** [comment]
same but the error code is 403 Forbidden.

**Comment by bigtunacan** [comment]
+1

Never been able to get this service to work so far; only get 403 forbidden or 503 service unavailable.

**Comment by c2h2** [comment]
noted, google api changed.

**Comment by c2h2** [comment]
will fix this week.

**Comment by c2h2** [comment]
fixed 53765d9b60b42c5a2a071cbd7cbbe8a672dc197e
