### ISSUE TITLE
Problem Saving the file to a specific location

### ISSUE THREAD

**Issue by jailan** [c2h2/tts#8]
It doesn't save it in the specified path or directory. Instead, It generates a "temp.mp3" file in the root directory of my rails app.
 Here's how I use it in my controller: "Hello".to_file "en", "/assets/test.mp3"

**Comment by c2h2** [comment]
have you tried with different path? do you have directory "/assets" in your linux system?

**Comment by jailan** [comment]
No /assets path in my linux system. The assets path referred to is the assets path in Rails Application root.

Was this gem developed to be intended for use with a Rails app?

**Comment by c2h2** [comment]
you need an existing dir.
